"""
forge.product_compiler.agents.integrator — Assembles generated code into a project.

Stage 7 of the pipeline: takes app.py + test files + schema and produces
a complete, runnable project with README, requirements, entry point, etc.
"""

from __future__ import annotations

import structlog
from pathlib import Path

from forge.product_compiler.models import DatabaseSchema, FailingTestSuite, IntegrationResult, RuleSet

log = structlog.get_logger(__name__)


class IntegratorAgent:
    """
    Assembles the project output from all prior stages.
    In Layer 2 this writes: README, requirements.txt, config, migrations.
    Layer 3+ adds: Docker, CI/CD, deployment configs.
    """

    def __init__(self, workdir: Path | str = Path("."), sandbox=None):
        self.workdir = Path(workdir)
        self.sandbox = sandbox

    def run(
        self,
        rule_set: RuleSet,
        test_suite: FailingTestSuite,
        app_file: str,
        schema: DatabaseSchema | None = None,
    ) -> IntegrationResult:
        """
        Assemble all generated artifacts into a runnable project.
        """
        result = IntegrationResult()

        # 1. Write README
        readme = self._generate_readme(rule_set, test_suite)
        readme_path = self.workdir / "README.md"
        readme_path.write_text(readme)
        result.readme_path = str(readme_path)
        result.files_generated.append(str(readme_path))
        log.info("integrator.wrote_readme", path=str(readme_path))

        # 2. Write requirements.txt
        reqs = self._generate_requirements(test_suite)
        reqs_path = self.workdir / "requirements.txt"
        reqs_path.write_text(reqs)
        result.requirements_path = str(reqs_path)
        result.files_generated.append(str(reqs_path))
        log.info("integrator.wrote_requirements", path=str(reqs_path))

        # 3. Write schema.sql if schema was provided
        if schema and schema.raw_sql:
            sql_path = self.workdir / "schema.sql"
            sql_path.write_text(schema.raw_sql)
            result.files_generated.append(str(sql_path))
            log.info("integrator.wrote_schema", path=str(sql_path))

            # Atlas: generate versioned migration from schema.sql if Atlas is installed
            if schema.migration_dir:
                self._apply_atlas_migration(schema, result.files_generated)

        # 4. Verify app.py exists
        app_path = self.workdir / "app.py"
        if app_path.exists():
            result.entry_point = str(app_path)

        result.project_dir = str(self.workdir)
        log.info("integrator.complete", files=len(result.files_generated))
        return result

    def _generate_readme(self, rule_set: RuleSet, test_suite: FailingTestSuite) -> str:
        """Generate a project README from rule set and test suite."""
        rules_summary = "\n".join(f"- {r.condition} → {r.action}" for r in rule_set.rules[:10])
        if len(rule_set.rules) > 10:
            rules_summary += f"\n- ... and {len(rule_set.rules) - 10} more rules"

        test_count = len(test_suite.test_cases)
        test_names = "\n".join(f"- {t.description}" for t in test_suite.test_cases[:15])
        if len(test_suite.test_cases) > 15:
            test_names += f"\n- ... and {len(test_suite.test_cases) - 15} more tests"

        return f"""# Generated Project

Auto-generated by Forge Product Compiler.

## Rules ({len(rule_set.rules)} total)
{rules_summary}

## Test Suite ({test_count} tests)
{test_names}

## Setup

```bash
pip install -r requirements.txt
pytest test_product.py
```

## Run

```bash
python app.py
```

## Architecture

- `app.py` — FastAPI application
- `test_product.py` — pytest test suite
- `schema.sql` — PostgreSQL schema (if applicable)
"""

    def _generate_requirements(self, test_suite: FailingTestSuite) -> str:
        """Generate requirements.txt based on framework and language."""
        reqs = [
            "pytest>=8.0.0",
            "pytest-asyncio>=0.23.0",
            "httpx>=0.27.0",  # for test client
        ]

        # Check for FastAPI in test code
        for tc in test_suite.test_cases:
            code = tc.test_code.lower()
            if "fastapi" in code or "fastapi" in str(code):
                reqs.insert(0, "fastapi>=0.110.0")
                reqs.insert(1, "uvicorn>=0.27.0")
                break
            elif "flask" in code:
                reqs.insert(0, "flask>=3.0.0")
                break

        return "\n".join(sorted(set(reqs)))

    def _apply_atlas_migration(self, schema, files_generated: list) -> None:
        """
        Generate a versioned migration file from schema.raw_sql using Atlas.

        Creates a migration file in schema.migration_dir (e.g. migrations/)
        and updates schema.migration_status and schema.last_migration_applied.
        """
        from forge.code_intelligence import Atlas

        am = Atlas.discover()
        if not am:
            log.warning("integrator.atlas.not_found", hint="Install: curl -fsSL https://atlasproject.io/install.sh | sh")
            return

        migrations_path = self.workdir / schema.migration_dir
        migrations_path.mkdir(exist_ok=True)

        # Write the desired schema as Atlas's schema.sql
        atlas_hcl = migrations_path / "schema.sql"
        if not atlas_hcl.exists():
            atlas_hcl.write_text(schema.raw_sql)

        # Create a new migration from the diff between current and desired state
        new_migrations = am.new_migration(
            url="postgres://localhost:5432/dev",  # placeholder; user overrides at apply time
            dir=str(migrations_path),
        )

        if new_migrations:
            latest = new_migrations[-1]
            schema.last_migration_applied = latest.version
            schema.migration_status = "pending"
            files_generated.append(str(latest.path))
            log.info(
                "integrator.atlas.migration_created",
                version=latest.version,
                path=str(latest.path),
            )
        else:
            log.warning("integrator.atlas.no_migration_generated")
