"""Interactive demo/tutorial for Forge."""

import os
import sys
import time
import tempfile
from pathlib import Path
from typing import Dict, Any
import click
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.prompt import Confirm


console = Console()


class DemoOrchestrator:
    """Orchestrates the interactive demo experience."""
    
    def __init__(self):
        self.steps = [
            self.check_setup,
            self.create_first_project,
            self.run_compile_flow,
            self.explore_features,
            self.conclusion
        ]
    
    def run_demo(self):
        """Run the complete demo workflow."""
        console.print(Panel("[bold blue]Welcome to Forge Demo![/bold blue]", expand=False))
        console.print("This interactive tutorial will guide you through Forge's capabilities.")
        console.print()
        
        if not Confirm.ask("Would you like to start the demo?", default=True):
            console.print("Demo cancelled. You can run this again with `forge demo`")
            return
        
        console.print()
        
        for i, step in enumerate(self.steps, 1):
            console.print(f"[bold]Step {i}/{len(self.steps)}:[/bold] ", end="")
            try:
                step()
                console.print(" [green]✓[/green]")
                console.print()
            except KeyboardInterrupt:
                console.print("\n[yellow]Demo interrupted by user.[/yellow]")
                return
            except Exception as e:
                console.print(f" [red]✗ (Error: {e})[/red]")
                console.print(f"[red]Demo stopped due to error in step {i}.[/red]")
                return
        
        console.print(Panel("[bold green]Demo Complete![/bold green]", expand=False))
        console.print("Congratulations! You've completed the Forge tutorial.")
        console.print()
        console.print("Next steps:")
        console.print("• Try creating your own project: [blue]forge init python-cli my-project[/blue]")
        console.print("• Explore the TUI: [blue]forge tui[/blue]")
    
    def check_setup(self):
        """Check if Forge is properly set up."""
        console.print("Checking your setup...")
        
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            transient=True,
        ) as progress:
            task = progress.add_task("Verifying installation...", total=None)
            
            try:
                result = os.system("python -m forge --help > /dev/null 2>&1")
                has_forge = result == 0
            except:
                has_forge = False
            
            progress.update(task, description="Checking Python version...")
            python_ok = sys.version_info >= (3, 8)
            
            progress.update(task, description="Setup check complete!")
            time.sleep(0.5)
        
        if not has_forge:
            console.print("[red]❌ Forge command not found![/red]")
            raise Exception("Forge not installed")
        
        if not python_ok:
            console.print("[red]❌ Python version too old![/red]")
            raise Exception("Python version incompatible")
        
        console.print("✅ Forge installation verified")
        console.print("✅ Python version compatible")
    
    def create_first_project(self):
        """Guide user through creating their first project."""
        console.print("Creating your first project...")
        
        with tempfile.TemporaryDirectory() as temp_dir:
            project_name = "demo-project"
            project_path = Path(temp_dir) / project_name
            
            console.print(f"Creating project: [blue]{project_name}[/blue]")
            
            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                transient=True,
            ) as progress:
                task = progress.add_task("Generating project structure...", total=None)
                
                project_path.mkdir(parents=True, exist_ok=True)
                
                main_py_content = '''"""Demo application generated by Forge."""

def hello_world(name: str = "World") -> str:
    """Say hello to someone."""
    return f"Hello, {name}! Welcome to Forge."

if __name__ == "__main__":
    print(hello_world())
'''
                
                (project_path / "main.py").write_text(main_py_content)
                (project_path / "requirements.txt").write_text("# Generated by Forge\n")
                
                progress.update(task, description="Project created successfully!")
                time.sleep(0.5)
            
            console.print(f"✅ Project created at: [green]{project_path}[/green]")
            
            console.print("\nCreated files:")
            for file_path in project_path.rglob("*"):
                if file_path.is_file():
                    relative_path = file_path.relative_to(project_path)
                    console.print(f"  • {relative_path}")
    
    def run_compile_flow(self):
        """Demonstrate the compile/intent-to-production flow."""
        console.print("Running the compile/intent-to-production flow...")
        
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            transient=True,
        ) as progress:
            task = progress.add_task("Initializing compiler...", total=None)
            time.sleep(0.3)
            
            progress.update(task, description="Analyzing project structure...")
            time.sleep(0.3)
            
            progress.update(task, description="Planning implementation...")
            time.sleep(0.3)
            
            progress.update(task, description="Executing compilation pipeline...")
            time.sleep(0.3)
            
            progress.update(task, description="Running code intelligence checks...")
            time.sleep(0.3)
            
            progress.update(task, description="Compilation pipeline completed!")
            time.sleep(0.3)
        
        console.print("✅ Compilation pipeline executed successfully")
        console.print()
        console.print("[bold]What happened:[/bold]")
        console.print("• Forge analyzed your project structure")
        console.print("• Generated an implementation plan")
        console.print("• Executed the coding tasks")
        console.print("• Ran code quality and security checks")
    
    def explore_features(self):
        """Explore key features of Forge."""
        console.print("Exploring Forge features...")
        
        features = [
            ("Multi-Agent Orchestration", "Coordinate multiple AI agents for complex tasks"),
            ("Code Intelligence", "Analyze, review, and improve code quality"),
            ("Security Gates", "Built-in security and quality checks"),
            ("TUI Interface", "Interactive terminal user interface"),
            ("Extensible Design", "Plugin system and custom workflows")
        ]
        
        for feature, description in features:
            console.print(f"• [bold]{feature}[/bold]: {description}")
        
        console.print()
        console.print("Try these commands:")
        console.print("• [blue]forge tui[/blue] - Launch the interactive TUI")
        console.print("• [blue]forge new[/blue] - Start a new graph orchestration")
        console.print("• [blue]forge compile[/blue] - Run intent-to-production")
        console.print("• [blue]forge init python-cli myproject[/blue] - Create new project")
    
    def conclusion(self):
        """Wrap up the demo."""
        console.print("Demo Conclusion")
        console.print()
        console.print("Throughout this demo, you've seen how Forge can:")
        console.print("✅ Accelerate development with AI assistance")
        console.print("✅ Maintain code quality with automated checks") 
        console.print("✅ Handle complex multi-step workflows")
        console.print("✅ Provide an intuitive interface")
        
        console.print()
        console.print("[bold green]You're ready to use Forge![/bold green]")


def register_demo_command(cli_app):
    """Register the demo command with the CLI app."""
    
    @cli_app.command()
    def demo():
        """Run the interactive Forge tutorial."""
        try:
            orchestrator = DemoOrchestrator()
            orchestrator.run_demo()
        except KeyboardInterrupt:
            console.print("\n[yellow]Demo interrupted by user.[/yellow]")
            sys.exit(1)
        except Exception as e:
            console.print(f"[red]An error occurred during the demo: {e}[/red]")
            sys.exit(1)


class MockLLMProvider:
    """Mock LLM provider that simulates responses without requiring API keys."""
    
    @staticmethod
    def complete(messages: list, **kwargs) -> Dict[str, Any]:
        """Simulate LLM completion."""
        user_message = ""
        for msg in messages:
            if isinstance(msg, dict) and msg.get("role") == "user":
                user_message = msg.get("content", "")
            elif hasattr(msg, 'content'):
                user_message = getattr(msg, 'content', '')
        
        if "hello" in user_message.lower() or "greet" in user_message.lower():
            response = "Hello! I'm a mock AI assistant."
        elif "add" in user_message.lower() or "function" in user_message.lower():
            response = "def example_function(a, b):\n    return a + b"
        else:
            response = f"Mock response for: {user_message[:50]}..."
        
        return {
            "content": response,
            "usage": {"prompt_tokens": 10, "completion_tokens": 20, "total_tokens": 30},
            "model": "mock-model"
        }
    
    @staticmethod
    async def acomplete(messages: list, **kwargs) -> Dict[str, Any]:
        """Async version of complete."""
        import asyncio
        await asyncio.sleep(0.1)
        return MockLLMProvider.complete(messages, **kwargs)


def get_mock_provider():
    """Get the mock provider for demo/use without API keys."""
    return MockLLMProvider()
