"""
forge.runners.common — Shared types, constants, and helpers for all runners.
"""

from __future__ import annotations
import re
from pathlib import Path
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from forge.llm import LLMBackend
    from forge.skills import SkillRegistry


# ── Skill injection ─────────────────────────────────────────────────────────────

def inject_skills_into_context(
    task_type: str,
    skill_registry: "SkillRegistry",
    llm: "LLMBackend | None",
) -> tuple[list, list[str]]:
    """
    Match and load relevant skills for a task type.
    Returns (matched_skills, skill_summaries_for_prompt).
    """
    if not skill_registry:
        return [], []
    from forge.skills import Skill

    matched = skill_registry.match(task_type)
    summaries = []
    for s in matched:
        summaries.append(f"[skill:{s.name}] {s.description}")
    return matched, summaries


# ── System prompts ─────────────────────────────────────────────────────────────

ORCHESTRATOR_SYSTEM = """You are the Orchestrator in a directed-graph agentic coding system (forge).
You receive a user prompt and must decide the next action.

Available actions:
- generate_spec: User has a vague idea, produce a concrete SPEC.md first
- executor: User has a spec, generate code files
- done: All work is complete
- delegate: Offload a specific subtask to a subagent

Respond ONLY with a JSON object: {"action": "generate_spec"|"executor"|"done"|"delegate", "reason": "...", "subagent_type": "..."}
"""


SPEC_GEN_SYSTEM = """You are the Spec Generator in a directed-graph agentic coding system (forge).
Given a user prompt, produce a complete, detailed SPEC.md.
Include: project name, overview, features list, file tree, acceptance criteria, tech stack.
Use markdown. Output ONLY the SPEC.md content.

IMPORTANT: Ask clarifying questions FIRST if the request is vague.
Ask at most 3 focused questions. Wait for answers before generating the spec.
"""


EXECUTOR_SYSTEM = """You are the Executor in a directed-graph agentic coding system (forge).
You have a SPEC.md. Generate all the code files described.

IMPORTANT — TDD-FIRST WORKFLOW:
1. Write tests BEFORE implementation code
2. Then write implementation to make tests pass
3. Verify all tests pass

IMPORTANT — SURGICAL EDITS:
For EXISTING files you want to change, use action "patch" with a surgical patch format.
NEVER use action "update" on existing files — it causes unnecessary diff noise.
Only use "create" for genuinely new files.

PATCH FORMAT for existing files (action: "patch"):
Output a JSON entry: {"path": "...", "action": "patch", "patch": "..."}
The patch text uses this format:
*** Begin Patch
*** Update File: path/to/file.py
@@ context line that uniquely identifies location
-old line to remove
+new line to add
  context line (unchanged, for anchoring)
*** End Patch

Rules for patches:
- Each chunk starts with @@ followed by a context line
- Lines starting with - are removed from the original
- Lines starting with + are added to the original
- Unchanged context lines (prefixed with space) anchor the match
- Use multiple chunks for discontiguous changes
- For additions at end of file, use @@ as the last line of the file
- For deletions, omit the + line entirely

For new files, use: {"path": "...", "action": "create", "content": "..."}
For deletions, use: {"path": "...", "action": "delete"}
"""


REVIEW_SYSTEM = """You are the Review Gate in a directed-graph agentic coding system (forge).
Review the generated files against the spec. Check:
1. All spec features are implemented
2. Code is syntactically correct
3. Files match the described file tree
4. Tests exist and cover the implementation

Respond ONLY with JSON: {"pass": true|false, "reason": "...", "issues": ["..."]}
"""


# ── Shared helpers ─────────────────────────────────────────────────────────────

ShortTermMemory = dict


def build_spec_changelog(prompt: str, new_spec: str, existing: Optional[str]) -> str:
    """Build changelog string for a new spec version."""
    if not existing:
        return f"- v1: Initial spec generated from prompt: {prompt[:60]}"
    return f"- v1: Initial spec\n- v2: Updated from prompt: {prompt[:60]}\n"


def generate_stub_spec(prompt: str) -> str:
    """Generate a stub SPEC.md when no LLM is available."""
    return f"""# SPEC.md — Generated

## Project
{prompt}

## Overview
Generated by forge.

## Features
- TBD based on prompt: {prompt}

## Files to Generate
- `src/` — source code
- `tests/` — test files
- `README.md`

## Acceptance Criteria
1. Code compiles/runs without errors
2. Tests pass
3. Matches spec above

## Tech Stack
- Language: Python 3.11+
- Testing: pytest
"""


def review_spec_compliance(executor_output: dict, spec_md: str) -> dict:
    """Stub review gate — used when LLM is unavailable or response is unparseable."""
    return {"pass": True, "reason": "auto-pass (stub)"}


def write_files(files: list[dict], workdir: Path) -> list[str]:
    """Write files to disk. Handles create, update, patch, delete actions.

    action "patch": parses the custom V4A patch format and applies surgically.
    action "update": full-file replacement (legacy).
    action "create"/"write": full-file write.
    action "delete": remove file.
    """
    from forge.patch import parse_patch as _parse_patch
    from forge.patch import apply_patch as _apply_patch

    written = []
    patch_hunks_by_path: dict[str, list] = {}

    # First pass: collect patch hunks (don't apply yet — patches need path context)
    for f in files:
        if not isinstance(f, dict):
            continue
        rel_path = f.get("path", "")
        if not rel_path:
            continue
        action = f.get("action", "create")

        if action == "patch":
            patch_text = f.get("patch", "")
            if not patch_text:
                continue
            try:
                result = _parse_patch(patch_text)
                hunks = result.get("hunks", [])
                if rel_path in patch_hunks_by_path:
                    patch_hunks_by_path[rel_path].extend(hunks)
                else:
                    patch_hunks_by_path[rel_path] = hunks
            except Exception:
                continue

    # Second pass: apply patches first, then do full-file ops
    for f in files:
        if not isinstance(f, dict):
            continue
        rel_path = f.get("path", "")
        if not rel_path:
            continue
        action = f.get("action", "create")
        content = f.get("content", "")
        target = workdir / rel_path

        if action == "patch":
            hunks = patch_hunks_by_path.get(rel_path, [])
            if not hunks:
                continue
            try:
                result = _apply_patch(hunks, workdir)
                written.extend(result.get("modified", []))
                written.extend(result.get("added", []))
                written.extend(result.get("deleted", []))
            except Exception as e:
                import structlog
                log = structlog.get_logger(__name__)
                log.warning("write_files.patch_failed", path=rel_path, error=str(e))
            continue

        if action == "delete":
            if target.exists():
                target.unlink()
                written.append(str(target))
        elif action in ("create", "write", "update"):
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            written.append(str(target))

    return written


def run_tests(workdir: Path) -> Optional[dict]:
    """
    Run pytest on the project directory. Returns structured test results
    from pytest-json-report output.

    Runs: pytest --json-report --json-report-file=results.json -q
    Then reads and deletes results.json. Falls back to regex-parsed stdout
    if the JSON file is unavailable (pytest-json-report not installed).
    """
    import json, subprocess, os

    json_report = workdir / "results.json"

    try:
        result = subprocess.run(
            ["python", "-m", "pytest",
             "--json-report", "--json-report-file=results.json", "-q"],
            cwd=str(workdir),
            capture_output=True,
            text=True,
            timeout=120,
        )
    except FileNotFoundError:
        # pytest not found at all
        return None
    except subprocess.TimeoutExpired:
        return {"total": 0, "failed": -1, "output": "timeout", "failures": []}
    except Exception as e:
        return {"total": 0, "failed": -1, "output": str(e), "failures": []}

    # Read structured JSON report
    if json_report.exists():
        try:
            with open(json_report) as f:
                report = json.load(f)
            os.unlink(json_report)
            return _parse_pytest_json_report(report)
        except Exception:
            # Corrupt or unreadable — fall through to stdout parse
            pass

    # Fallback: parse stdout/stderr with regex (pytest-json-report not installed)
    output = result.stdout + result.stderr
    return _parse_pytest_fallback(output)


def _parse_pytest_json_report(report: dict) -> dict:
    """
    Parse pytest-json-report JSON output into the same schema as _parse_pytest_fallback.

    pytest-json-report schema (v2):
      report["summary"]  → {"passed": N, "failed": N, "total": N, ...}
      report["tests"]    → list of test entries with nodeid, outcome, call.longrepr

    longrepr (failure message) can be a string or a (message, longstr) tuple
    or a pytest repr record. We extract whatever is serializable to string.
    """
    summary = report.get("summary", {})
    total = summary.get("total", 0)
    failed_count = summary.get("failed", 0)
    passed_count = summary.get("passed", 0)
    if total == 0:
        total = passed_count + failed_count

    failures = []
    for entry in report.get("tests", []):
        if entry.get("outcome") != "failed":
            continue

        nodeid = entry.get("nodeid", "")

        # Extract failure message from call.longrepr
        message = ""
        failure_type = "Error"
        call_section = entry.get("call", {})
        longrepr = call_section.get("longrepr")

        if longrepr:
            # longrepr can be: str, list [msg, str], or a pytest ExceptionRepr
            if isinstance(longrepr, str):
                message = longrepr
            elif isinstance(longrepr, list):
                message = str(longrepr[0]) if longrepr else ""
            else:
                # DAPRepr or ExceptionRepr — extract whatever str() gives
                message = str(longrepr)

        # Extract assertion message if present (AssertionError format)
        if "AssertionError" in message:
            failure_type = "AssertionError"

        # Parse file + line from nodeid: "tests/test_foo.py::test_bar"
        file_part = nodeid.split("::")[0] if "::" in nodeid else nodeid
        line_no = entry.get("lineno") or ""

        failures.append({
            "name": nodeid,
            "file": file_part,
            "line": str(line_no) if line_no else "",
            "type": failure_type,
            "message": message.strip(),
        })

    raw_summary = (
        f"{passed_count} passed, {failed_count} failed"
        if summary else ""
    )

    return {
        "total": total,
        "failed": failed_count,
        "passed": passed_count,
        "output": raw_summary,
        "failures": failures,
        "_report": report,  # full report available for tools that need it
    }


def _parse_pytest_fallback(output: str) -> dict:
    """
    Regex fallback for when pytest-json-report is not available.
    Parses pytest stdout/stderr into structured failure summaries.
    """
    import re
    failed = 0
    total = 0
    failures = []
    current: dict = {}

    for line in output.splitlines():
        stripped = line.strip()

        # Summary line: "1 failed, 3 passed" or "4 passed" or "1 failed"
        if " failed" in stripped or " passed" in stripped:
            m_failed = re.search(r"(\d+) failed", stripped)
            m_passed = re.search(r"(\d+) passed", stripped)
            if m_failed:
                failed = int(m_failed.group(1))
            if m_passed:
                total = int(m_passed.group(1)) + failed
            elif failed and not m_passed:
                total = failed
            continue

        # FAILED marker: "tests/test_billing.py::test_stripe_webhook FAILED"
        if " FAILED" in stripped:
            if current and current.get("name"):
                failures.append(current)
            parts = stripped.split(" FAILED ", 1)
            file_test = parts[0]
            current = {
                "name": file_test,
                "type": "unknown",
                "message": "",
                "file": file_test.split("::")[0] if "::" in file_test else file_test,
            }
            continue

        # Failure reason lines
        if current and stripped:
            if stripped.startswith("AssertionError:"):
                current["type"] = "AssertionError"
                current["message"] = stripped[len("AssertionError:"):].strip()
            elif stripped.startswith(("Error:", "Exception:", "ImportError:", "ModuleNotFoundError:", "TypeError:", "ValueError:", "TimeoutError:", "FileNotFoundError:")):
                if current["type"] == "unknown":
                    label = stripped.split(":")[0]
                    current["type"] = label
                    current["message"] = stripped[len(label) + 1:].strip()
                else:
                    current["message"] = (current["message"] + " " + stripped).strip()
            elif current["message"]:
                current["message"] = (current["message"] + " " + stripped).strip()

        # Location hints
        if current and re.search(r'(line|error|raised):', stripped, re.IGNORECASE):
            m = re.search(r"([\w./]+.py):(\d+)", stripped)
            if m and current.get("file") == "unknown":
                current["file"] = m.group(1)
                current["line"] = m.group(2)

    if current and current.get("name"):
        failures.append(current)

    if failed == 0 and total == 0:
        m = re.search(r"(\d+) passed", output)
        total = int(m.group(1)) if m else 0

    return {
        "total": total,
        "failed": failed,
        "output": output[:1000],
        "failures": failures,
    }


def generate_from_spec(spec_md: str) -> list[dict]:
    """Generate stub files when no LLM is available."""
    return [
        {"path": "README.md", "action": "create", "content": "# Project\n\n" + spec_md[:200]},
        {"path": "src/__init__.py", "action": "create", "content": ""},
        {"path": "tests/test_main.py", "action": "create", "content": "def test_placeholder(): assert True"},
    ]


def apply_patch_files(hunks: list, workdir: Path) -> dict:
    """Apply patch hunks to filesystem. Returns {added, modified, deleted}."""
    from forge.patch import apply_patch
    return apply_patch(hunks, workdir)
