"""
forge.runners.common — Shared types, constants, and helpers for all runners.
"""

from __future__ import annotations
import re
from pathlib import Path
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from forge.llm import LLMBackend
    from forge.skills import SkillRegistry


# ── Skill injection ─────────────────────────────────────────────────────────────

def inject_skills_into_context(
    task_type: str,
    skill_registry: "SkillRegistry",
    llm: "LLMBackend | None",
) -> tuple[list, list[str]]:
    """
    Match and load relevant skills for a task type.
    Returns (matched_skills, skill_summaries_for_prompt).
    """
    if not skill_registry:
        return [], []
    from forge.skills import Skill

    matched = skill_registry.match(task_type)
    summaries = []
    for s in matched:
        summaries.append(f"[skill:{s.name}] {s.description}")
    return matched, summaries


# ── System prompts ─────────────────────────────────────────────────────────────

ORCHESTRATOR_SYSTEM = """You are the Orchestrator in a directed-graph agentic coding system (forge).
You receive a user prompt and must decide the next action.

Available actions:
- generate_spec: User has a vague idea, produce a concrete SPEC.md first
- executor: User has a spec, generate code files
- done: All work is complete
- delegate: Offload a specific subtask to a subagent

Respond ONLY with a JSON object: {"action": "generate_spec"|"executor"|"done"|"delegate", "reason": "...", "subagent_type": "..."}
"""


SPEC_GEN_SYSTEM = """You are the Spec Generator in a directed-graph agentic coding system (forge).
Given a user prompt, produce a complete, detailed SPEC.md.
Include: project name, overview, features list, file tree, acceptance criteria, tech stack.
Use markdown. Output ONLY the SPEC.md content.

IMPORTANT: Ask clarifying questions FIRST if the request is vague.
Ask at most 3 focused questions. Wait for answers before generating the spec.
"""


EXECUTOR_SYSTEM = """You are the Executor in a directed-graph agentic coding system (forge).
You have a SPEC.md. Generate all the code files described.

IMPORTANT — TDD-FIRST WORKFLOW:
1. Write tests BEFORE implementation code
2. Then write implementation to make tests pass
3. Verify all tests pass

For each file output a JSON entry: {"path": "...", "action": "create"|"update"|"delete", "content": "..."}.
Only include files that need to be created/updated.
"""


REVIEW_SYSTEM = """You are the Review Gate in a directed-graph agentic coding system (forge).
Review the generated files against the spec. Check:
1. All spec features are implemented
2. Code is syntactically correct
3. Files match the described file tree
4. Tests exist and cover the implementation

Respond ONLY with JSON: {"pass": true|false, "reason": "...", "issues": ["..."]}
"""


# ── Shared helpers ─────────────────────────────────────────────────────────────

ShortTermMemory = dict


def build_spec_changelog(prompt: str, new_spec: str, existing: Optional[str]) -> str:
    """Build changelog string for a new spec version."""
    if not existing:
        return f"- v1: Initial spec generated from prompt: {prompt[:60]}"
    return f"- v1: Initial spec\n- v2: Updated from prompt: {prompt[:60]}\n"


def generate_stub_spec(prompt: str) -> str:
    """Generate a stub SPEC.md when no LLM is available."""
    return f"""# SPEC.md — Generated

## Project
{prompt}

## Overview
Generated by forge.

## Features
- TBD based on prompt: {prompt}

## Files to Generate
- `src/` — source code
- `tests/` — test files
- `README.md`

## Acceptance Criteria
1. Code compiles/runs without errors
2. Tests pass
3. Matches spec above

## Tech Stack
- Language: Python 3.11+
- Testing: pytest
"""


def review_spec_compliance(executor_output: dict, spec_md: str) -> dict:
    """Stub review gate — used when LLM is unavailable or response is unparseable."""
    return {"pass": True, "reason": "auto-pass (stub)"}


def write_files(files: list[dict], workdir: Path) -> list[str]:
    """Write files to disk. Returns list of written paths."""
    written = []
    for f in files:
        if not isinstance(f, dict):
            continue
        rel_path = f.get("path", "")
        if not rel_path:
            continue
        action = f.get("action", "create")
        content = f.get("content", "")

        target = workdir / rel_path
        if action == "delete":
            if target.exists():
                target.unlink()
                written.append(str(target))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            written.append(str(target))
    return written


def run_tests(workdir: Path) -> Optional[dict]:
    """Run pytest on the project directory. Returns structured test results."""
    import subprocess

    try:
        result = subprocess.run(
            ["python", "-m", "pytest", "--tb=short", "-q"],
            cwd=str(workdir),
            capture_output=True,
            text=True,
            timeout=120,
        )
        output = result.stdout + result.stderr
        return parse_pytest_output(output)
    except FileNotFoundError:
        return None
    except subprocess.TimeoutExpired:
        return {"total": 0, "failed": -1, "output": "timeout", "failures": []}
    except Exception as e:
        return {"total": 0, "failed": -1, "output": str(e), "failures": []}


def parse_pytest_output(output: str) -> dict:
    """
    Parse pytest stdout/stderr into structured failure summaries.
    Extracts test name, file, failure type, and message for each failure.
    """
    failed = 0
    total = 0
    failures = []

    # Track current failure context
    current: dict = {}

    for line in output.splitlines():
        stripped = line.strip()

        # Summary line: "1 failed, 3 passed" or "4 passed" or "1 failed"
        if " failed" in stripped or " passed" in stripped:
            m_failed = re.search(r"(\d+) failed", stripped)
            m_passed = re.search(r"(\d+) passed", stripped)
            if m_failed:
                failed = int(m_failed.group(1))
            if m_passed:
                total = int(m_passed.group(1)) + failed
            elif failed and not m_passed:
                total = failed
            continue

        # FAILED marker: "tests/test_billing.py::test_stripe_webhook FAILED"
        if " FAILED" in stripped:
            if current and current.get("name"):
                failures.append(current)
            parts = stripped.split(" FAILED ", 1)
            file_test = parts[0]
            current = {
                "name": file_test,
                "type": "unknown",
                "message": "",
                "file": file_test.split("::")[0] if "::" in file_test else file_test,
            }
            continue

        # Failure reason lines (AssertionError, ImportError, etc.)
        if current and stripped:
            if stripped.startswith("AssertionError:"):
                current["type"] = "AssertionError"
                current["message"] = stripped[len("AssertionError:") :].strip()
            elif stripped.startswith(("Error:", "Exception:", "ImportError:", "ModuleNotFoundError:", "TypeError:", "ValueError:", "TimeoutError:", "FileNotFoundError:")):
                if current["type"] == "unknown":
                    label = stripped.split(":")[0]
                    current["type"] = label
                    current["message"] = stripped[len(label) + 1 :].strip()
                else:
                    current["message"] = (current["message"] + " " + stripped).strip()
            elif current["message"]:
                current["message"] = (current["message"] + " " + stripped).strip()

        # Location hints within traceback
        if current and re.search(r'(line|error|raised):', stripped, re.IGNORECASE):
            m = re.search(r"([\w./]+.py):(\d+)", stripped)
            if m and current.get("file") == "unknown":
                current["file"] = m.group(1)
                current["line"] = m.group(2)

    # Append last failure
    if current and current.get("name"):
        failures.append(current)

    # All-passed edge case
    if failed == 0 and total == 0:
        m = re.search(r"(\d+) passed", output)
        total = int(m.group(1)) if m else 0

    return {
        "total": total,
        "failed": failed,
        "output": output[:1000],
        "failures": failures,
    }


def generate_from_spec(spec_md: str) -> list[dict]:
    """Generate stub files when no LLM is available."""
    return [
        {"path": "README.md", "action": "create", "content": "# Project\n\n" + spec_md[:200]},
        {"path": "src/__init__.py", "action": "create", "content": ""},
        {"path": "tests/test_main.py", "action": "create", "content": "def test_placeholder(): assert True"},
    ]


def apply_patch_files(hunks: list, workdir: Path) -> dict:
    """Apply patch hunks to filesystem. Returns {added, modified, deleted}."""
    from forge.patch import apply_patch
    return apply_patch(hunks, workdir)
